---
# roles/dockhand/tasks/main.yml

- name: Install dockhand
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Configure dockhand
  ansible.builtin.include_tasks: configure.yml
  tags: configure
