---
# roles/dockhand/handlers/main.yml

- name: Restart dockhand
  community.docker.docker_compose_v2:
    project_src: "{{ dockhand_config_dir }}"
    state: present
    recreate: always
  listen: "Restart dockhand"
